### ISSUE TITLE
Plugin not able to load

### ISSUE THREAD

**Issue by thielfab** [jakimowb/bit-flag-renderer#1]
```
Couldn't load plugin 'BitFlagRenderer' 

ModuleNotFoundError: No module named 'bitflagrenderer' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins/BitFlagRenderer/__init__.py", line 1, in 
    from .bitflagrenderer.plugin import BitFlagRendererPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins/BitFlagRenderer/bitflagrenderer/plugin.py", line 21, in 
    from bitflagrenderer import TITLE
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'bitflagrenderer'


Python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] 
QGIS version: 3.28.5-Firenze Firenze, 50adba36f2 

Python Path:
/usr/share/qgis/python
/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python
/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python
.
```

Ubuntu 22.04.01

**Comment by thielfab** [comment]
Can not reproduce anymore, so issue gone with recent QGIS and plugin versions.
